### ISSUE TITLE
Device discovery times out

### ISSUE THREAD

**Issue by dwmw2** [madgeni/alexa_domo#10]
Alexa only gives us 20 seconds to discover devices, but we make a huge number of *separate* connections to the Domoticz server, each with their own SSL negotiation.

When I test locally, or even using the 'Test' button in AWS, at least they all seem to run in parallel. But used 'in anger' from Alexa, it runs a lot slower and times out. I wonder if the number of threads is being restricted in that case, which makes the difference. 

I think it should be possible to get everything we need with a single request for `/json.htm?type=devices&used=true&filter=all`

That lists all scenes/groups and devices, each with a `PlanID` field which, if non-zero, tells us which room a device is in. So we can preserve the existing behaviour of only showing devices which are in room plans — although as a way to filter which devices Alexa sees, that's a fairly strange choice given that Domoticz can already filter devices per-user.

**Comment by madgeni** [comment]
accepted
