### ISSUE TITLE
Fails to use IPv6

### ISSUE THREAD

**Issue by dwmw2** [madgeni/alexa_domo#11]
When I specify the server as an IPv6 address, it works fine. If I use the hostname though, it ends up connecting over Legacy IP. RFC3484 says it should use IPv6 first and only fall back to Legacy IP if that fails...

When I watch its DNS lookups with tcpdump I see it's doing the AAAA lookup and getting a result... but just ignoring it.

**Comment by madgeni** [comment]
rfc6724 supercedes this - and makes no default choice, rather horses for courses. Given the scope and scale of this code, i'd like to adhere to the KISS methodology.

**Comment by dwmw2** [comment]
Thanks for the reference to RFC6724; I hadn't noticed that RFC3484 had been updated. I'm not sure it really changes the matter though. The priority table was always "configurable", and for some reason the system's settings aren't being honoured here. Probably not strictly an alexa_domo problem; it'll be in one of the modules that's being used. I should chase it up there.
