### ISSUE TITLE
"Setting Lounge heat to unknown temperature"

### ISSUE THREAD

**Issue by dwmw2** [madgeni/alexa_domo#14]
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference#settargettemperatureconfirmation indicates that the `temperatureMode` and `previousState` members of the `SetTargetTemperatureConfirmation` message are mandatory, but we don't send them.

This is presumably why Alexa says she's set the temperature to "unknown temperature".

**Comment by madgeni** [comment]
made the change, will test tonight - again, Amazon are updating their API and documentation, with no notifications possible. When I first wrote this, there were no mandatory fields and payload was to be empty. Assume that's why it still works - deprecated rather than removed :)

**Comment by dwmw2** [comment]
Thanks. It's non-trivial for me to test as my temperature devices are evohome, and the existing `uTemp()` API function does very bad things for that; I need to use the  `setused` method as shown in the 'Updating a setpoint using the JSON API' section at https://www.domoticz.com/wiki/Evohome#More_info

**Comment by madgeni** [comment]
Cool - change made, can you test? thanks

**Comment by dwmw2** [comment]
Thanks. I can't test that until I fix evohome `(devType.startsWith("Heating") && device.subType === "Zone")` devices to submit set point updates with a request to `/json.htm?type=setused&idx=<idx>&setpoint=<setpoint>&mode=<mode>&used=true` as noted above.

I noticed Alexa saying "unknown temperature" first... and *then* I noticed that the system had gone haywire because we were overwriting the data strangely.

**Comment by fergalom** [comment]
Just tried it, works a perfect for me.

If you could add celsius or fahrenheit after the temperature, that would be rolls royce version

**Comment by madgeni** [comment]
I would love to fergalom, but sadly with Smart Home Skills i have no control over the utterances :(

**Comment by dwmw2** [comment]
Alexa's voice interface is configurable; it can be switched to use °F. All communication with backend devices is in °C though, as is sane. It's only the voice part which can be locally changed to do archaic crap.

**Comment by madgeni** [comment]
it will not allow me to add words to the responses. It reports in C, but I can't tell it to say Celsius

**Comment by madgeni** [comment]
Happy if i close this?

**Comment by Lyr3x** [comment]
i recognised that alexa is responding in german:
_Heizung Heizung wird auf 21° gestellt_ in english for you _thermostat thermostat will be set to 21°_
in english alexa is just saying _Okay_ which is fine for me, but maybe you can fix the double thermostat 👍

**Comment by madgeni** [comment]
Hi - 
is this still an issue?

**Comment by madgeni** [comment]
closing pending someone shouting at me :)
