### ISSUE TITLE
Connection failure not reported

### ISSUE THREAD

**Issue by dwmw2** [madgeni/alexa_domo#15]
Yesterday, Alexa started telling me "that function is not supported for that device" when I told her to turn the lights on. Closer inspection showed that my Domoticz system wasn't reachable from the outside world, but the error wasn't being reported. This probably should have resulted in a [TargetBridgeConnectivityUnstableError](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference#targetbridgeconnectivityunstableerror)

**Comment by madgeni** [comment]
Ok - this should now handle connection issues with individual domoticz hosts. please test
