### ISSUE TITLE
22 Devices

### ISSUE THREAD

**Issue by Lyr3x** [madgeni/alexa_domo#4]
I have another issue. I just discover 23 devices: there is one Scene missing, and 5 devices. Any ideas :)?

**Comment by nigels0** [comment]
That happens to me occasionally - you just need to keep discovering devices on your Echo (or Dot). I suspect it is down to the 20 seconds allowed for the fetch and processing. I did update the configuration advanced settings to 10 seconds (I'm discovering 50 devices)in the Lambda

**Comment by Lyr3x** [comment]
Just repeat and repeat and pray?

**Comment by Lyr3x** [comment]
hm i cant get more than 23 👎 . Setted the timout time to 10 seconds as well

**Comment by madgeni** [comment]
and you have more than 23 devices in your room plans?
I genuinely don't know where the latency gets introduced - usual local discovery <500 ms, my code's not 'too' bad. If it's not latency introduced between you and the lambda, then i'm not sure what's happening tbh. 
the logging is currently active, is it not picking up >23 devices in the code, or is it just hitting the max timeout?

**Comment by Lyr3x** [comment]
oh... i forgot it 👯‍♂️
