### ISSUE TITLE
No results if final room has no devices

### ISSUE THREAD

**Issue by dwmw2** [madgeni/alexa_domo#7]
Since commit 9de85b8ebdf02fab03c187e353e8b0d73cfbd7fc in `getRoomDevices()` we now return immediately if there are no devices in the room. Without ever decrementing `k` and invoking `returnme()` for the last room.

Having said that, I'm not sure we should fetch devices separately for each room anyway. Why not just fetch *all* devices, then assign them to the correct rooms? All those separate requests are taking too long and causing Alexa to time out for me when discovering devices.

**Comment by madgeni** [comment]
The original discovery ran through getAllDevices, however the consensus was to control discovery to Alexa via Rooms in Domoticz. This makes a lot of sense if you have a lot of devices and only want a subset for voice control. 
There is no way to ascertain which room they should be in via the Domoticz API without using my method. I'm surprised it's timing out for you - how many rooms + devices do you have? 
I will take a look at resolving the issue around not sending any devices if 1 room has devices,and others do not - however the easiest solution is to either delete the room on your side, or add some devices to it!

**Comment by dwmw2** [comment]
I have 14 rooms/plans and 0-3 active devices in each. It's not huge. In testing it runs in 8 seconds or so, but for some reason it's longer when Alexa uses it 'in anger', and thus it fails. I can see from the timestamps in the AWS logs that the results are being shown more than 20 seconds after the request.

If I fetch all devices, they do seem to have both 'PlanID' and 'PlanIDs' fields which indicate which rooms they're in....

**Comment by dwmw2** [comment]
The bug with empty rooms is fairly simply resolved; I'll submit a PR.

For filtering... I'm not sure why you want to limit Alexa only to the devices which are assigned to rooms. Domoticz can already limit the devices which are visible to a given user, and Alexa can (and arguably *should*) have her own login to Domoticz. Oh, and it looks like if you do, we get the following crash because a filtered-out device still gets listed in the `GetPlanDevices` output but then the `GetDevice` call fails for it:
```
/home/local/ANT/dwmw/git/alexa_domo/domapi.js:258
                for (var i = 0; i < devArray.length; i++) {
                                            ^

TypeError: Cannot read property 'length' of undefined
    at /home/local/ANT/dwmw/git/alexa_domo/domapi.js:258:45
    at Request._callback (/home/local/ANT/dwmw/git/alexa_domo/node_modules/domoticz-api/api/domoticz.js:88:13)
    at Request.self.callback (/home/local/ANT/dwmw/git/alexa_domo/node_modules/domoticz-api/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)

```

**Comment by dwmw2** [comment]
Closing this now; I'll open a new issue for the discovery timeouts.
